version: "3"
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.2.11
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_CREATE_TOPICS: order:1:1
    redis:
        image: redis
        ports:
            - "6379:6379"
    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        volumes:
            - ./script/mysql:/docker-entrypoint-initdb.d/
    seckill:
        build: "./service/seckill"
        ports:
            - "8081:8080"
        depends_on:
            - kafka
            - redis
    order:
        build: "./service/order"
        depends_on:
            - kafka
            - mysql
    inventory:
        build: "./service/inventory"
        depends_on:
            - redis
            - mysql
    product:
        build: "./service/product"
        depends_on:
            - mysql
    nginx:
        image: nginx
        ports:
            - "8080:8080"
        volumes:
            - ./script/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - product
            - inventory
            - seckill
