version: "3"
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 192.168.2.11
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_PORT: "9092"
    redis:
        image: redis
        ports:
            - "6379:6379"
    mysql:
        image: mysql
        ports:
            - "3306:3006"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
    api:
        build: "./api"
        ports:
            - "8080:8080"
        depends_on:
            - kafka
            - redis
            - mysql
        links:
            - redis
